<?php
/**
 * Created by PhpStorm.
 * Author Terry Lucas
 * Date 17.10.12
 * Time 15:18
 */

namespace TerryLucas2017\Pattern\Structural\Decorator;


/**
 * Class Bird
 * Author Terry Lucas
 * @package TerryLucas2017\Pattern\Structural\Decorator
 */
class Bird extends Fish
{

    /**
     * @author Terry Lucas
     * Bird constructor.
     * @param IWuKong|WuKong $wuKong
     */
    public function __construct($wuKong)
    {
        parent::__construct($wuKong);
    }

    /**
     * @author Terry Lucas
     * @return string
     */
    public function say(): string
    {
        return parent::say(); // TODO: Change the autogenerated stub
    }

    /**
     * @author Terry Lucas
     * @return string
     */
    public function fly(): string
    {
        return 'fly to fly';
    }
}