<?php
/**
 * Created by PhpStorm.
 * Author Terry Lucas
 * Date 17.10.12
 * Time 14:52
 */

namespace TerryLucas2017\Pattern\Structural\Decorator;

/**
 * Class ConcreteDecorator
 * Author Terry Lucas
 * @package TerryLucas2017\Pattern\Structural\Decorator
 */
class ConcreteDecorator extends Decorator
{
    /**
     * @author Terry Lucas
     */
    public function sampleOperation()
    {
        parent::sampleOperation(); // TODO: Change the autogenerated stub
    }
}