<?php
/**
 * Created by PhpStorm.
 * Author Terry Lucas
 * Date 17.10.12
 * Time 15:03
 */

namespace TerryLucas2017\Pattern\Structural\Decorator;


/**
 * Class Fish
 * Author Terry Lucas
 * @package TerryLucas2017\Pattern\Structural\Decorator
 */
class Fish extends WuKong72Bian
{

    /**
     * @author Terry Lucas
     * Fish constructor.
     */
    public function __construct(IWuKong $wuKong)
    {
        parent::__construct($wuKong);
    }

    /**
     * @author Terry Lucas
     * @return string
     */
    public function say(): string
    {
        return parent::say(); // TODO: Change the autogenerated stub
    }

    /**
     * @author Terry Lucas
     * @return string
     */
    public function swim()
    {
        return 'swimming';
    }
}